# Generated by Django 5.2.8 on 2025-12-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_seed_subscription_plans'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_projects', to='organization.organizationmember'),
        ),
        migrations.AlterField(
            model_name='project',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects', to='organization.organizationmember'),
        ),
    ]
