# Generated by Django 5.0.7 on 2025-10-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('organization', '0007_seed_subscription_plans'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization making the subscription payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('project', 'Project Payment'), ('subscription', 'Subscription Payment')], default='project', help_text='Type of payment (project or subscription)', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription this payment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='organization.organizationsubscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client who made the payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client'),
        ),
    ]
